### ISSUE TITLE
Grub vs grub2

### ISSUE THREAD

**Issue by logicguy1** [Lxtharia/minegrub-theme#12]
Hey there, so im trying to install this absolutely wonderful project but i have a folder "/boot/grub" but not "/boot/grub2", cant seem to find much about the issue, got any recurses or tips?

**Comment by Lxtharia** [comment]
Hi, as noted in the README, it shouldn't matter. The chances are very high that you have grub version 2, because its been out since 2012. You can check your grub version with `grub-install -V` and it should give you an output like `grub-install (GRUB) 2:2.06.r403...` so you should be all good.
Its maybe just nicer to have a grub folder without an ugly number in it :)
