### ISSUE TITLE
Rescaling

### ISSUE THREAD

**Issue by GTP95** [Lxtharia/minegrub-theme#15]
Hi! 
I really like your theme, but I've got an issue. I have 6 boot menu entries on my laptop, which means that, if I use the formula you provide in the `theme.txt` file, the bottom bar ends up outside the screen. Is there a way to rescale everything so it fits my screen?
Good job btw (and I use Arch too btw ;) )!

**Comment by GTP95** [comment]
I removed a duplicated entry so now it fits my screen, but I'm leaving this issue open for now just in case you're interested in providing a way to rescale the theme.

**Comment by Lxtharia** [comment]
Hey, it should be as simple as changing the value `top = 30%` in the `boot_menu` sections to something like `top = 30%`, and adjust the static bar image as well `top = 30%+calculated_value`

extra info:
top is just the amount of pixels from the top, the reason there are two `boot_menu` sections are so we can have shadow (the white text is the first boot_menu section and gets drawn with a little offset to the left and top (more extra extra info: the reason why it says `40%+14` is, because the layer with the white text doesnt have a 17px pixmap border or something and therefore would get drawn 17 pixels higher than the layer below (where the buttons are) would, then add the offset of -3 and we have 14.)

extra text:
to actually rescale the theme and make elements smaller/larger would require the font to be regenerated with a different font size and the pixmaps would need to be adjusted as well i think. 
I like writing comment essays. If you have any more questions, feel free to reopen this issue or make a new one, maybe i will have figured out how to get email notifications from github until then
