### ISSUE TITLE
Consider moving to Codeberg

### ISSUE THREAD

**Issue by MagicLike** [Lxtharia/minegrub-theme#18]
- GitHub is
  - privacy-invasive
  - Microsoft-owned
  - proprietary
  - vendor-lock-in
  - Tor-hostile
- [GitHub Copilot™ attacks copyleft licensing](https://nogithub.codeberg.page/)

Moving the whole repo and all code over to [Codeberg](https://codeberg.org) would be great, as it is a libre, free, open-source, privacy-friendly and non-profit Git platform from Germany, running the Gittea soft-fork [Forgejo](https://forgejo.org).

- https://codeberg.org/Recommendations/Mirror_to_Codeberg
- https://nogithub.codeberg.page

If you need any help with the transfer I am happy to assist.

**Comment by addy** [comment]
Is this an ad?

**Comment by lukeocodes** [comment]
This doesn't look like a bug 👀

**Comment by benne** [comment]
Is this a joke?

**Comment by MagicLike** [comment]
> Is this an ad?

no it isn't. I am just concerned about the future of FOSS/FLOSS software, as I think we (we as the whole open source community) need to move to open source platforms.

**Comment by MagicLike** [comment]
> This doesn't look like a bug eyes

If you see what GitHub is developing towards - it might be

**Comment by MagicLike** [comment]
> Is this a joke?

nope, see https://github.com/Lxtharia/minegrub-theme/issues/18#issuecomment-1645160661

Also it would be nice if we could all just recognise others opinions instead of framing them as "joke" or "ad", etc..

**Comment by MagicLike** [comment]
To be clear - I don't want to force my opinion on anyone. I just made my point about my concern with GitHub.

**Comment by br4yd** [comment]
Even though many seem to frame this suggestion as an "ad" (which doesn't make sense for a non-profit) I'd also appreciate moving to Codeberg. The author has some valid points that are valid for discussion IMO. Just downvoting it and asking if it's a joke is not helping tbh.

**Comment by PetrosKatiforis** [comment]
It's concerning seeing that the majority is against this suggestion... You're most likely using gnu code and should be thankful that some programmers dedicated a large part of their life to (among others) prevent Microsoft from maintaining yet another monopoly on operating systems. Please educate yourself about the free software foundation and what the future holds. I used to think that Github was the good option out there, but turns out it isn't. I'm switching to codeberg and deleting this account today. You're programmers, if you aren't open-minded then we're all doomed hahaha, I'm dead serious

**Comment by addy** [comment]
I'm not against the suggestion, I love my account on SourceHut. It's just that it doesn't seem genuine as the OP is heavily integrated into GitHub themselves. 

It also seems like a very strange thing to post on a random repository that you aren't directly involved with. It raised a few of my red flags related to certain tech evangelists.

**Comment by PetrosKatiforis** [comment]
It is a call from the Software Freedom Conservancy, they instructed their members to spread the message by specifically listing an alternative: https://sfconservancy.org/GiveUpGitHub/.

To anybody reading this, the choice is yours but regardless, you should invest some time and think about it! The transition is easy, I have it setup already

**Comment by lukeocodes** [comment]
Judging by the increase rate in comments, this issue has reached a pro-switch reddit

**Comment by MagicLike** [comment]
> I'm not against the suggestion, I love my account on SourceHut. It's just that it doesn't seem genuine as the OP is heavily integrated into GitHub themselves. 
> 
> It also seems like a very strange thing to post on a random repository that you aren't directly involved with. It raised a few of my red flags related to certain tech evangelists.

Yes, I am - but only for forks and commits to other projects on here. My personal projects have all been moved over to Codeberg.

The reason why I opened this issue on a "random" repo is, that I really like this little project and want it to be preserved and therefore want to throw some thoughts in the room if GitHub is a great place for it.

Btw: I also brought this thought up in all projects I am more heavily involved in.

**Comment by lukeocodes** [comment]
> Yes, I am - but only for forks and commits to other projects on here. My personal projects have all been moved over to Codeberg.

Answer me these. What do you think will happen to my open source and propriatary code that is hosted on GitHub?

**Comment by Andre601** [comment]
I myself switched my website, blog and some projects to Codeberg, tho I won't move everything to it...
Main reason is that I use GitHub Actions. And while they do offer their own CI instance using Woodpecker-CI does it not allow all the stuff Actions does here...

Tho, on the other hand do I quite like their Codeberg pages service. it's quite decent. Especially in terms of configuring (sub-)domains to use for a repo.

One downside I noticed there however is, that when you use a domain for a user/org will sub-pages for repositories no longer work.
What I mean is, that a repository named `subpage` with a `pages` branch will show up on `example.codeberg.page/subpage` (Assuming it's under a user/org named example) while it won't for `example.com/subpage`, assuming the `pages` repository used is set to use example.com as its domain.

Another minor inconvenience is that page content always has to be on a pages branch. Even on the `pages` repo (Trust me... I tried it. The docs are misleading here).

Either way, I'm all for a move given GitHub's recent developments on certain things.
Tho I can understand if a move is not considered...

Although, using the mirror system on codeberg, you could keep this repository here as a mirror, so that people still can check things out.
(A mirror from GitHub to codeberg isn't prohibited, but they recommend not to do it for heavy/large ones and not just to have a "backup" or smth)

**Comment by ntdesmond** [comment]
Quality of their services is promising, lol

![image](https://github.com/Lxtharia/minegrub-theme/assets/29694249/540b2fd4-1269-4005-9173-a4d2b6bc4c47)

Note the date of planned work here: `July 30 2023` :trollface:

**Comment by Andre601** [comment]
Site works fine for me.

Also, they did had a lot of automated crawlers and alike targeting their site alongside some bad Database queries taking a ton of time to process, which they are working on fixing.

They also have a scheduled maintenance on august 10th to update their Git system.

**Comment by MagicLike** [comment]
Also works perfectly fine for me...

**Comment by olivertzeng** [comment]
# PLEASE SHUT DOWN THIS UNRELATED ISSUE WHY ARE THERE SO MANY UNRELATED ISSUES BRUH

**Comment by olivertzeng** [comment]
> - GitHub is
> 
>   - privacy-invasive
> 
>   - Microsoft-owned
> 
>   - proprietary
> 
>   - vendor-lock-in
> 
>   - Tor-hostile
> 
> - [GitHub Copilot™ attacks copyleft licensing](https://nogithub.codeberg.page/)
> 
> 
> 
> Moving the whole repo and all code over to [Codeberg](https://codeberg.org) would be great, as it is a libre, free, open-source, privacy-friendly and non-profit Git platform from Germany, running the Gittea soft-fork [Forgejo](https://forgejo.org).
> 
> 
> 
> - https://codeberg.org/Recommendations/Mirror_to_Codeberg
> 
> - https://nogithub.codeberg.page
> 
> 
> 
> If you need any help with the transfer I am happy to assist.

You're using GitHub lol @MagicLike 
![image](https://github.com/Lxtharia/minegrub-theme/assets/86348833/73950bc6-2e17-4889-8dda-f2024f2fe098)

**Comment by MagicLike** [comment]
As this issue is getting way too heated and therefore can't be a place for a calm discussion whilst being able to talk to each other on the same level, I will close this issue now.

**Comment by MagicLike** [comment]
As this issue is getting way too heated and therefore can't be a place for a calm discussion whilst being able to talk to each other on the same level, I will close this issue now.

**Comment by Lxtharia** [comment]
Thanks, I've been putting this off from the start and thought "Yea, maybe I will put it up on codeberg some day", but tbh, I've been rolling with github so far, it's what people are most familiar with, and I don't have the energy to switch, when github still works well.

**Comment by MagicLike** [comment]
> Thanks, I've been putting this off from the start and thought "Yea, maybe I will put it up on codeberg some day", but tbh, I've been rolling with github so far, it's what people are most familiar with, and I don't have the energy to switch, when github still works well.

Alright! :+1:
